sudo: false
language: scala

jdk:
- openjdk8

scala:
- 2.12.10

script:
- sbt ++$TRAVIS_SCALA_VERSION orgScriptCI
- sbt ++$TRAVIS_SCALA_VERSION publishLocal scripted

after_success:
- sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess

before_cache:
- find $HOME/.sbt -name "*.lock" -type f -delete
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.coursier/cache"
  - "$HOME/.sbt"

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_baee6defd129_key -iv $encrypted_baee6defd129_iv -in secret_key.asc.enc -out secret_key.asc -d;
    gpg --import --batch --passphrase "$PGP_PASSPHRASE" secret_key.asc;
  fi

install:
- rvm use 2.6.5 --install --fuzzy
- gem install jekyll -v 4
